### ISSUE TITLE
Black frame around the camera

### ISSUE THREAD

**Issue by ibober** [ibober/ZrobymAR#9]
Hide or fill with something black frames around the camera, example:
![image](https://cloud.githubusercontent.com/assets/8260211/20029968/482ee240-a36c-11e6-971e-ae53750657d7.png)

**Comment by ibober** [comment]
for now is hidden with stripes

**Comment by cezanVBE** [comment]
did you manage to fix the black frame? I have the same problem with my app and can't find a solution

**Comment by ibober** [comment]
actually no. I've made interface in front of these black stripes.
but I'm sure with new version 6 of ARToolKit it is possible though I haven't tried
